name: kalkulator_dart
description: A simple command-line calculator app in Dart.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  math_expressions: ^2.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
